# Generated by Django 6.0 on 2025-12-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('id_verified', models.CharField(max_length=100)),
                ('uhid', models.CharField(max_length=100)),
                ('reference_id', models.CharField(max_length=50)),
                ('vaccination_status', models.CharField(max_length=150)),
                ('vaccinated_by', models.CharField(max_length=150)),
                ('vaccinated_at', models.CharField(max_length=200)),
                ('dose_number', models.CharField(max_length=30)),
                ('dose_date', models.DateField()),
                ('vaccine_name', models.CharField(max_length=50)),
                ('batch_number', models.CharField(max_length=50)),
                ('vaccine_type', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
            ],
        ),
    ]
