# Generated by Django 6.0 on 2026-01-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('email', models.CharField()),
                ('school_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('math', models.IntegerField()),
                ('hindi', models.IntegerField()),
                ('science', models.IntegerField()),
                ('sst', models.IntegerField()),
                ('english', models.IntegerField()),
            ],
        ),
    ]
