# Generated by Django 6.0 on 2026-01-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_alter_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
